# Generated by Django 6.0.6 on 2026-07-23 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sos', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTimeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('resident', 'Resident'), ('guardian', 'Guardian'), ('volunteer', 'Volunteer'), ('security', 'Security'), ('admin', 'Admin')], max_length=20)),
                ('response_window_minutes', models.IntegerField(default=5)),
                ('auto_escalate', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EscalationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_role', models.CharField(choices=[('resident', 'Resident'), ('guardian', 'Guardian'), ('volunteer', 'Volunteer'), ('security', 'Security'), ('admin', 'Admin')], max_length=20)),
                ('to_role', models.CharField(choices=[('resident', 'Resident'), ('guardian', 'Guardian'), ('volunteer', 'Volunteer'), ('security', 'Security'), ('admin', 'Admin')], max_length=20)),
                ('reason', models.TextField()),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('sos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_logs', to='sos.sos')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
