# Generated by Django 6.0.6 on 2026-07-23 13:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentupdate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sos',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='sos.emergencycategory'),
        ),
        migrations.AddField(
            model_name='sos',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sos_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidentupdate',
            name='sos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='sos.sos'),
        ),
    ]
